#Dependencies: https://pypi.org/project/python-steam-api/ and https://pypi.org/project/PyYAML/
#Get your Steam Web API key: https://steamcommunity.com/dev/apikey
#Ascii character <, >, :, ", /, \, |, ?, * are not allowed in Windows filename for default

remove_char:
    - "<"
    - ">"
    - ":"
    - '"'
    - "'"
    - "/"
    - "\\"
    - "|"
    - "?"
    - "*"
    - " "

path: D:\Test
steam_api_key: 00000000000000000000000000000000

